"""Trilha 1 — Gerenciar e comandar agentes. Fontes: inemaeventos/<slug>/index.html + shared/acesso.json (lidas em 28/09/2026)."""
MODULES=[]
FIGURES={}
def M(title,goal,lab,steps,check,answer,topics,snippet,sources,slug):
    MODULES.append(dict(title=title,goal=goal,lab=lab,steps=steps,check=check,answer=answer,
                        topics=topics,snippet=snippet,sources=sources,slug=slug))
def T(title,what,why,keys,example,action):
    return dict(title=title,what=what,why=why,keys=keys,example=example,action=action)

# ---------------------------------------------------------------- Módulo 0 · Gestão de IA
M('Gestão de IA: 2027, o ano de gerenciar agentes',
  'Explicar por que a empresa com agentes precisa de gestão, e não só de tecnologia, usando as 8 competências e o LOOP-R.',
  'Sua ficha de gestão de um agente',
  ['Escolha um processo da sua empresa que hoje roda só com pessoas e escreva, em uma linha, o resultado que ele entrega.',
   'Responda à pergunta da página: se eu tivesse humanos, agentes e automações hoje, esse processo ainda existiria desse jeito? Liste o que existe por hábito e o que existe por exigência real.',
   'Para a etapa que ficaria com um agente, preencha: papel, objetivo, contexto, ferramentas, autonomia (faz sozinho, confirma, jamais executa) e como será avaliado.',
   'Confira a ficha contra as 8 competências: cada uma precisa ter pelo menos uma linha. A competência sem resposta é o módulo da formação por onde você deve entrar.'],
  'Uma equipe montou um agente numa tarde e ele já executa o fluxo de aprovação de 2010, só que mais rápido. O que a área Gestão de IA diria?',
  'Que ele entrega o erro mais rápido: antes de automatizar, o processo precisa ser desmontado e redesenhado, e o agente precisa de dono, alçada, medida e custo por resultado.',
  [T('A tese: gerenciar o que se criou',
     'A área Gestão de IA do eventos.inema.pro abre com uma frase: "2026 ensinamos a criar agentes. 2027 é o ano de aprender a gerenciá-los." Um agente é uma IA que recebe uma responsabilidade e executa trabalho com ferramentas, em vez de só responder uma pergunta. Gerenciar esse agente significa dar papel, objetivo, contexto, ferramentas, alçada e avaliação, como sempre se fez com pessoas. A página traz ainda uma decisão mais dura: não colocar agentes para executar processos antigos mais rápido, e sim redesenhar a empresa para a velocidade dos agentes. A área junta a tese, as 8 competências do gestor de IA, o LOOP-R, a Formação Gestão de IA 2027 e os cursos e projetos do INEMA que já cobrem a maior parte do caminho.',
     'Criar um agente deixou de ser o gargalo. O que trava a empresa é o que vem depois: quem responde por ele, o que pode fazer sozinho, como se mede e quanto custa. Entender a tese muda a pergunta de "qual ferramenta?" para "como eu gerencio isso?".',
     'Gestão de pessoas + gestão de processos + gestão de agentes; é gestão, não só tecnologia; redesenhar antes de acelerar.',
     'Uma gerente administrativa já tem três agentes montados pela equipe, cada um feito por uma pessoa diferente. Ninguém sabe quem aprova o que eles produzem nem quanto custam por mês. O problema dela não é construir o quarto agente; é gerenciar os três que existem.',
     'Liste os agentes ou automações com IA que sua equipe já usa e, ao lado de cada um, escreva o nome de quem responde pelo resultado.'),
   T('O terceiro objeto da gestão',
     'A página mostra as eras da gestão, cada uma respondendo ao que a empresa tinha para coordenar. De 1980 a 2000, gestão de pessoas: cargo, responsabilidade, ferramentas, limites e avaliação. De 2000 a 2020, gestão de processos: desenhar, documentar, treinar e executar. De 2020 a 2025, transformação digital: desenhar, automatizar e monitorar; de 2025 a 2026, construção de agentes, com prompts, skills, contexto, tools e memória. Em 2027, a gestão coordena humanos, agentes, modelos, processos e orçamento computacional ao mesmo tempo. A área é para a empresa que já tem agentes e precisa gerenciá-los; a construção do agente em si fica na área AGI-ready.',
     'Quem trata agente como projeto de TI deixa de fora a parte que decide o resultado: responsabilidade, limites e medida. Ver o agente como terceiro objeto da gestão coloca o assunto na mesa de quem administra.',
     'Três mudanças: criar ficou fácil, gerenciar não; o processo antigo não merece ser acelerado; o processo deixa de ser congelado.',
     'Um escritório coloca um agente para seguir o mesmo fluxo de conferência que três pessoas faziam em papel. O agente é rápido, mas repete as etapas que só existiam porque antes não havia outra forma. A pergunta certa teria sido se aquele fluxo ainda deveria existir.',
     'Escolha um processo seu e marque em qual era ele foi desenhado: pessoas, processos, digital ou agentes.'),
   T('Gerenciar agentes como pessoas',
     'A tese central da página é que gerenciar agentes se parece muito com a velha gestão de pessoas, só que com mais medida. Trocam-se as palavras, não a lógica: funcionário, cargo, responsabilidade, ferramentas, limites e avaliação viram agente, papel, objetivo, contexto, ferramentas, autonomia e avaliação. Entram dois itens que pessoas não tinham: contexto explícito e autonomia graduada. Autonomia graduada quer dizer que o agente não recebe "tudo ou nada", e sim uma alçada, ou seja, um limite do que decide sozinho. E o agente pode ser medido em praticamente tudo.',
     'Muitas regras que a empresa já conhece servem de novo, e isso encurta o caminho. Separação de funções, alçada e revisão humana não precisam ser inventadas para agentes; precisam ser aplicadas a eles.',
     'Contábil: quem lança não aprova; jurídico: o agente prepara, o advogado decide e assina; saúde: algumas decisões ficam fora da alçada do agente.',
     'Num escritório contábil, o agente lança e classifica os documentos do mês, mas a aprovação continua com outra pessoa. Como diz a página, o agente vai até a porta da assinatura, nunca além.',
     'Pegue a descrição de cargo de alguém da equipe e reescreva-a para um agente, acrescentando o contexto explícito e a alçada.'),
   T('As 8 competências do gestor de IA',
     'A página lista oito competências, na ordem em que um gestor as usa. Estratégia pergunta qual resultado queremos; arquitetura do trabalho, se o processo ainda deveria existir; delegação, o que exatamente entregar ao agente; orquestração, se é um agente ou vários, em série ou em paralelo. Governança decide o que ele faz sozinho, confirma ou jamais executa; economia pergunta quanto custa produzir o resultado; avaliação, se está bom e comparado a quê; evolução, o que aprendemos nesta execução. As quatro primeiras decidem o que o agente vai fazer, e as quatro últimas decidem se ele continua fazendo. O gerente de 2027 administra nove objetos, de pessoas e agentes até o orçamento computacional, e mede indicadores como custo por resultado, retrabalho e taxa de autonomia.',
     'As competências servem de checklist: se uma delas não tem resposta, é ali que o agente vai falhar. Também mostram onde estudar, porque a página indica em qual curso cada competência é ensinada hoje.',
     'Estratégia; arquitetura; delegação; orquestração; governança; economia; avaliação; evolução; custo por tarefa concluída.',
     'Uma equipe escolhe o modelo mais barato por token para um agente de atendimento. Ele erra e precisa de duas tentativas por caso. A página resume a conta: um agente barato que erra e precisa de duas tentativas custou o dobro da tabela.',
     'Dê uma nota de 0 a 2 para cada uma das 8 competências no seu agente principal e circule a mais baixa.'),
   T('Processo não é sagrado: o LOOP-R',
     'A página compara quatro gerações de processo. O tradicional era desenhado, documentado, treinado e executado; o automatizado, desenhado, automatizado e monitorado; o agêntico parte de um objetivo, o agente executa, mede, e um humano ou agente avalia. O LOOP-R fecha o ciclo: executar, observar, criticar, propor, experimentar, validar, promover e repetir. Assim o processo vira um sistema vivo, que tem versão como software. As regras são três: não automatize um processo ruim; humanos dirigem, agentes executam; promover e reverter são etapas, não acidentes.',
     'Sem o ciclo, a empresa pergunta só "a tarefa terminou?" e não aprende nada com cada execução. Com ele, a própria execução propõe a melhoria seguinte, e uma mudança que piorou o resultado é revertida sem drama.',
     'Quatro gerações; LOOP-R; processo com versão; promover e reverter; desmontar antes de automatizar.',
     'Um time de atendimento testa uma nova resposta padrão proposta pelo agente durante duas semanas. Como a taxa de retrabalho caiu, a mudança é promovida e vira a nova versão do processo; se tivesse piorado, voltaria à versão anterior.',
     'Desmonte um processo em etapas e marque cada uma como tarefa humana, agente, automação simples, Computer Use ou API.'),
   T('Formação 2027 e por onde começar',
     'A Formação Gestão de IA 2027 tem dez módulos e um projeto final, com o curso Gestão de IA como espinha dorsal. Os módulos vão da empresa agêntica, passando por processo não é sagrado, delegação e autonomia, economia dos agentes e governança, até a empresa que aprende com o LOOP-R. O projeto final é o Gestoria, um simulador de gestão de empresa agêntica em catorze passos. A página é honesta: a formação é o empacotamento de uma tese, não um curso novo publicado hoje, e entre 75% e 80% da base já existe em cursos e projetos abertos. A área reúne os cursos Gestão de IA, Os Super-Agentes Chegaram, Super-Agentes na prática, Arquiteto de Trabalho com IA, LOOP-R e Copilot + Agentes, e os projetos Gestoria, LOOP-R, Arquiteto de Execução, Agentic OS, Kit do Arquiteto de Agentes e Kit Copilot + Agentes.',
     'Saber o que já está no ar evita esperar por um curso que ainda vai ser empacotado. O caminho sugerido é entrar pelos cursos existentes, na ordem dos módulos.',
     'Dez módulos; Gestoria como projeto final; 75% a 80% da base já existe; o melhor primeiro módulo é um processo da sua empresa.',
     'Um dono de clínica quer começar, mas não sabe por qual curso. Ele pega o processo de agendamento, descobre que sua dúvida é sobre o que o agente pode fazer sozinho e entra pelo módulo de delegação e autonomia, apoiado em Super-Agentes.',
     'Abra https://eventos.inema.pro/gestao-ia/, leia a lista dos dez módulos e anote qual deles responde à sua dúvida de hoje.')],
  ('Prompt: diagnóstico de gestão de um agente',
   'Leia https://eventos.inema.pro/gestao-ia/ (área Gestão de IA do INEMA). Use as 8 competências da página (estratégia, arquitetura do trabalho, delegação, orquestração, governança, economia, avaliação, evolução) para avaliar o agente abaixo.\n\nMeu processo: <descreva o processo e quem faz cada etapa hoje>\nO agente: <o que ele faz, com quais ferramentas, quem aprova>\n\nEntregue: 1) uma tabela competência | como está hoje | o que falta; 2) a lista do que o agente faz sozinho, confirma e jamais executa; 3) três indicadores para medir o agente (use a lista de indicadores da página); 4) qual módulo da Formação Gestão de IA 2027 eu deveria estudar primeiro e por quê. Não invente dados do meu processo: onde faltar informação, pergunte.'),
  [('Área Gestão de IA','https://eventos.inema.pro/gestao-ia/'),
   ('Curso Gestão de IA','https://inematds.github.io/curso-gestao-ia/'),
   ('Gestoria (guia)','https://inematds.github.io/gestoria/guia/'),
   ('LOOP-R (curso)','https://inematds.github.io/loop-r/curso/')],
  'gestao-ia')

FIGURES[(0,2)] = dict(kind='timeline',
    caption='Cada era da gestão ganhou um objeto novo para coordenar; em 2027 os agentes se somam a pessoas e processos, sem substituí-los.',
    items=[('Pessoas','1980–2000'),('Processos','2000–2020'),('Digital','2020–2025'),('Construção','2025–2026'),('Gestão agentes','2027')])
FIGURES[(0,4)] = dict(kind='grid',
    caption='As quatro primeiras competências decidem o que o agente vai fazer; as quatro últimas decidem se ele continua fazendo.',
    items=['Estratégia','Arquitetura','Delegação','Orquestração','Governança','Economia','Avaliação','Evolução'])
FIGURES[(0,5)] = dict(kind='flow',
    caption='No LOOP-R a própria execução propõe a melhoria seguinte: o que é validado é promovido, e o ciclo se repete.',
    items=['Executar','Observar','Criticar e propor','Experimentar','Validar','Promover'])
FIGURES[(0,6)] = dict(kind='columns',
    caption='A formação se apoia no que já está publicado: cada coluna é um curso ou projeto que cobre uma parte da tese.',
    items=[('Gestão de IA','espinha dorsal'),('Super-Agentes','delegação'),('Arq. Trabalho','redesenho'),('LOOP-R','evolução'),('Gestoria','projeto final')])

# ---------------------------------------------------------------- Módulo 1 · AGI-ready
M('AGI-ready: seu trabalho vira comandar agentes',
  'Explicar a diferença entre dar ordens passo a passo e delegar a um agente, usando a escada intenção, objetivo, prompt, skill, contexto, ferramentas, memória, permissões e evals.',
  'Sua primeira delegação real',
  ['Escolha na sua lista de pedidos à IA da última semana um que seja responsabilidade, não tarefa com receita.',
   'Reescreva o pedido com as cinco peças da página: objetivo, o que importa, o que não pode acontecer, recursos disponíveis e como você vai julgar o resultado.',
   'Monte a matriz de confiança em três colunas (decide sozinho, propõe e eu aprovo, nunca toca), com um dono em cada linha.',
   'Envie o pedido pedindo um plano antes de qualquer ação e confira: o plano respeita as restrições e o critério de "bom" que você definiu? Anote o que faltou.'],
  'Seu pedido à IA tem 30 passos numerados e ainda assim o resultado sai errado quando um passo falta. O que a área AGI-ready propõe?',
  'Subir o nível do pedido: dizer o destino (objetivo, restrições, recursos e critério de sucesso) e colocar o "como fazer bem" num Skill reutilizável, em vez de ensinar cada passo.',
  [T('A IA parou de esperar ordens',
     'A área AGI-ready abre com a frase: "A IA parou de esperar ordens. Seu trabalho vira comandar agentes." A página lembra que, durante três anos, tentamos colocar a operação inteira dentro de um prompt gigante. Com agentes que trabalham por horas ou dias, o jogo muda: você diz o destino e o agente descobre o caminho. Um agente, aqui, é uma IA que recebe uma responsabilidade, planeja, executa, monitora e volta com o resultado. A área reúne o que está mudando, o modelo mental para acompanhar e os cursos e projetos do INEMA para começar hoje, sem programar.',
     'Quem continua operando a IA só por comandos curtos compete com o próprio agente. Quem aprende a delegar multiplica a própria capacidade, e isso se treina.',
     'Destino, não caminho; trabalhar por horas ou dias; delegar; comandar agentes sem programar.',
     'Um analista pedia à IA, todo mês, cinco comandos separados para montar o relatório de vendas. Passou a entregar a responsabilidade inteira, com objetivo e critério de pronto, e a revisar só o resultado.',
     'Escreva numa frase qual é o destino do trabalho que você mais repete, sem descrever nenhum passo.'),
   T('Tarefa vira responsabilidade',
     'A página descreve seis mudanças: as três primeiras vêm de quem está dentro dos laboratórios, e as três seguintes são o que isso significa na sua mesa. Na mesa, a primeira é que tarefa vira responsabilidade: você deixa de pedir "faça esta planilha" e passa a entregar "cuide da conciliação deste mês". A segunda é que confiança vira uma curva, não um interruptor: o que o agente decide sozinho, o que propõe e você aprova, o que nunca toca, cada linha com um dono. A terceira é que seu valor sobe para o que a IA não decide: definir o objetivo, escolher o que importa, dizer o que não pode acontecer e julgar se o resultado ficou bom. A página também cita, como fonte externa, um vídeo em inglês sobre o artigo "Alien Minds", de Jakub Pachocki, cientista-chefe da OpenAI, que admite que a capacidade cresce mais rápido que o controle.',
     'Sem essa troca de unidade, você continua escrevendo receitas para uma ferramenta que já consegue cuidar do resultado. E sem a curva de confiança, ou você trava tudo ou solta demais.',
     'Tarefa × responsabilidade; confiança como curva; matriz de confiança; papel de gerente de agentes.',
     'Uma coordenadora financeira entrega ao agente "cuide da conciliação deste mês". Ele classifica sozinho, propõe os ajustes para ela aprovar e nunca toca em pagamentos, cada linha com um responsável nomeado.',
     'Reescreva um pedido seu no formato "cuide de..." e liste o que o agente decide sozinho, o que propõe e o que nunca toca.'),
   T('O fim do prompt como programa inteiro',
     'A página avisa que falar em "fim do prompt" é uma simplificação exagerada: o prompt não desaparece. O que acaba é o prompt como programa inteiro, com toda a inteligência da operação escrita em linguagem natural, como se fazia entre 2023 e 2025. Micro-prompting é ensinar cada passo: faça A, depois B, depois C; se um passo falta, o resultado sai errado. Agora o prompt diz o objetivo, o que importa, as restrições, os recursos e o que conta como resultado bom. E ele trabalha junto com o Skill, que é conhecimento ou procedimento reutilizável: instruções, arquivos de referência, templates, scripts e orientações de uso de ferramentas.',
     'Separar prompt de Skill evita reescrever os mesmos nove passos toda vez. O prompt fica curto, e a qualidade vem do manual operacional que o agente já carrega.',
     'Prompt = o que quero agora (o briefing); Skill = como nossa organização costuma fazer; Prompt → Context → Skill → Agent Engineering → Orchestration.',
     'Você diz "transforme esta pesquisa em uma apresentação para empresários brasileiros". O Skill de apresentações traz a estrutura de narrativa, o padrão de slides, as regras de texto e o processo de revisão. O agente recebe prompt mais Skill e executa muito melhor.',
     'Pegue seu prompt mais longo e separe em duas colunas: o que muda a cada pedido (prompt) e o que é sempre igual (candidato a Skill).'),
   T('A escada de um agente que trabalha',
     'A página monta a arquitetura em níveis, com um mesmo exemplo: aumentar a conversão de um curso. Intenção responde "por quê?"; objetivo, "o quê?"; prompt é a orientação desta execução; Skill é como fazer bem, repetidamente. Depois vêm contexto (o que ele precisa saber), ferramentas (as mãos do agente, como navegador, CRM, planilhas, APIs e MCP), memória (a experiência acumulada) e, por fim, permissões e evals. Evals são testes que dizem se o resultado atende ao critério de sucesso; junto com limites, aprovação humana e logs, formam o controle de qualidade. Como resume a página, não queremos só um agente poderoso: queremos um agente controlável.',
     'Quando um agente falha, a escada mostra em qual degrau está o problema: faltou contexto, faltou Skill ou faltou critério. Sem ela, toda falha vira um prompt maior.',
     'Intenção; objetivo; prompt; skill; contexto; ferramentas; memória; permissões e evals; humano decide o destino e julga o resultado.',
     'No exemplo da página, um agente com cinco Skills (pesquisa, copy, campanha, vídeo e analytics) recebe uma frase curta: "lance este curso para empresários brasileiros e busque 200 matrículas". A frase dispara uma quantidade enorme de trabalho, porque o como já está nos Skills.',
     'Preencha os nove degraus da escada para um objetivo seu e marque o degrau que hoje está vazio.'),
   T('Seis movimentos para esta semana',
     'A página traduz a mudança em seis dicas que cabem na agenda. Primeira: separe tarefa de responsabilidade na sua lista de pedidos à IA. Segunda: reescreva um prompt como delegação, com objetivo, o que importa, o que não pode acontecer, recursos e como vai julgar, e peça um plano antes de qualquer ação. Terceira: se explicou o mesmo procedimento três vezes, transforme-o em Skill, com manual, template, checklist e exemplos. Quarta: escreva a matriz de confiança; quinta: dê contexto antes de dar ferramentas; sexta: defina o que é "bom" antes de rodar.',
     'São passos pequenos e verificáveis, não um projeto de meses. Cada um é o primeiro degrau de uma competência que a página lista: pensar processos, dirigir IA, construir agentes, integrar sistemas, avaliar e supervisionar, conhecer o negócio.',
     'Tarefa × responsabilidade; delegação em cinco peças; Skill do que se repete; matriz de confiança; contexto antes de ferramentas; eval antes de rodar.',
     'Uma consultora percebe que explicou três vezes como quer os relatórios de reunião. Ela junta o modelo, um checklist e dois exemplos num Skill; na quarta vez, o pedido cabe numa linha.',
     'Escolha uma das seis dicas e aplique hoje a um pedido real; anote o antes e o depois.'),
   T('Cursos, projetos e três portas',
     'A área reúne cursos para quem decide e não programa e cursos para quem quer construir. Para começar: Os Super-Agentes Chegaram (6 aulas), Super-Agentes na prática (8 aulas) e Arquiteto de Trabalho com IA (8 aulas). Para ir à ferramenta: Arquitetura de Intenção, Computer Use com o GPT-6 Astra, Subagentes e Superpowers, além da gravação Agentes do Zero: Fundamentos (5 dias). Os projetos com código e guia são OS Coach, os-agentes, Kit do Arquiteto de Agentes, INEMACCBOT, Content2Video, WebMCP Readiness, Fable 5.1 · Prompt de Sistema e STORM Research. A página fecha com três portas para o mesmo ecossistema: INEMA.CLUB (cursos abertos), INEMA.VIP (comunidade) e INEMA.PRO (plataforma prática).',
     'Cada projeto é um pedaço da arquitetura funcionando de verdade: o INEMACCBOT mostra a matriz de confiança em código, o WebMCP Readiness mostra o lado "tools" visto do site. Ver o exemplo pronto acelera a primeira delegação.',
     'Comece por Os Super-Agentes Chegaram; cursos abertos em português; projetos com código e guia; INEMA.CLUB, INEMA.VIP, INEMA.PRO.',
     'Um gestor sem experiência em programação faz primeiro Os Super-Agentes Chegaram, escreve a carta de delegação com as seis perguntas e só depois abre o Kit do Arquiteto de Agentes para transformar o agente numa especificação de uma página.',
     'Abra https://inematds.github.io/agi-ready/ e faça a primeira aula de Os Super-Agentes Chegaram.')],
  ('Prompt: transformar um pedido em delegação',
   'Leia https://eventos.inema.pro/agi-ready/ (área AGI-ready do INEMA), em especial a arquitetura (intenção, objetivo, prompt, skill, contexto, ferramentas, memória, permissões e evals) e as seis dicas.\n\nMeu pedido de hoje, do jeito que eu escrevo: <cole aqui seu prompt passo a passo>\nMinha área e o que já existe: <empresa, clientes, ferramentas disponíveis>\n\nReescreva como delegação, com cinco peças: objetivo, o que importa, o que não pode acontecer, recursos disponíveis e como vou julgar o resultado. Depois: 1) aponte quais partes são sempre iguais e deveriam virar um Skill; 2) monte a matriz de confiança (decide sozinho | propõe e eu aprovo | nunca toca); 3) diga qual degrau da arquitetura está faltando. Peça um plano antes de qualquer ação e não invente informações da minha empresa.'),
  [('Área AGI-ready','https://eventos.inema.pro/agi-ready/'),
   ('Os Super-Agentes Chegaram','https://inematds.github.io/agi-ready/'),
   ('Super-Agentes na prática','https://inematds.github.io/agi-pratica/'),
   ('Kit do Arquiteto de Agentes','https://inematds.github.io/kit-arquiteto-agentes/guia/')],
  'agi-ready')

FIGURES[(1,3)] = dict(kind='timeline',
    caption='Prompt Engineering não desaparece, evolui: a página situa o momento atual na era do Skill Engineering.',
    items=[('Prompt','Era 1'),('Contexto','Era 2'),('Skill','Era 3'),('Agente','Era 4'),('Orquestração','Era 5')])
FIGURES[(1,4)] = dict(kind='stack',
    caption='Cada degrau responde a uma pergunta diferente; permissões e evals no topo são o que torna o agente controlável.',
    items=[('Intenção','por quê?'),('Objetivo','o quê?'),('Prompt','esta execução'),('Skill','como fazer bem'),('Contexto e memória','o que ele sabe'),('Permissões e evals','controle de qualidade')])
FIGURES[(1,5)] = dict(kind='flow',
    caption='Os seis movimentos da semana seguem uma ordem: primeiro separar e delegar, depois dar contexto e definir o que é "bom".',
    items=['Tarefa × resp.','Delegação','Skill','Matriz confiança','Contexto','Definir "bom"'])
FIGURES[(1,6)] = dict(kind='columns',
    caption='Os três primeiros cursos são para quem decide e não programa; os demais entram na ferramenta.',
    items=[('Super-Agentes','comece aqui · 6 aulas'),('Na prática','8 aulas'),('Arq. Trabalho','processos · 8 aulas'),('Subagentes','orquestração'),('Kit Arquiteto','especificação')])

# ---------------------------------------------------------------- Módulo 2 · IA Cultivada
M('IA Cultivada: agente não se programa, se cultiva',
  'Explicar por que um agente melhora pelo ambiente que você cultiva, e não pelo modelo, usando os oito elementos, o ciclo e os cinco arquivos do kit.',
  'O primeiro jardim',
  ['Escolha um jardim (vida pessoal, Jarvis ou negócio) e uma única função para o agente.',
   'Escreva a ficha do agente: função, resultado esperado, dono humano, o que faz sozinho, o que pede confirmação e o que nunca faz, com versão v1.0 e data.',
   'Use o agente nessa função por uma semana e registre cada falha em uma linha no diário: data, o que quebrou, a menor correção possível, instrução ou infra.',
   'Na revisão semanal, transforme cada linha em mudança no contexto, nas regras, nos exemplos ou nas ferramentas e suba a ficha para v1.1. Confira: o que mudou está registrado no arquivo, não só na conversa?'],
  'Depois de um mês, você diz que "sua IA ficou melhor", mas o modelo é o mesmo. O que melhorou, segundo a área IA Cultivada?',
  'O jardim: contexto, memória, regras, exemplos e ferramentas que você ajustou a cada ciclo. Em uso o modelo não aprende sozinho; quem aprende é o sistema em volta dele.',
  [T('O processo que produz o comportamento',
     'A área IA Cultivada abre com a tese: "Antes, programávamos o comportamento. Agora, programamos o processo que produz o comportamento." Ninguém escreve linha por linha a capacidade de um grande modelo de fazer analogias ou planejar uma empresa: os laboratórios criam as condições e as capacidades emergem. A página separa dois níveis de cultivo. No nível 1, o laboratório cultiva o modelo, com arquitetura, dados, objetivo, compute, treinamento e feedback, e você não participa. No nível 2, você cultiva o agente: o modelo chega pronto, com os pesos congelados, e o que você cultiva é o envelope em volta dele.',
     'Essa distinção explica por que o mesmo modelo vira um estagiário confuso para uma pessoa e um profissional confiável para outra. O modelo é igual ao do seu concorrente; o jardim, não.',
     'Cultivar, não construir; nível 1 (modelo) × nível 2 (agente); pesos congelados; o que aprende é o sistema.',
     'Duas equipes usam o mesmo modelo para responder clientes. Uma tem uma página de contexto, exemplos anotados e regras escritas; a outra só abre o chat. A diferença de qualidade vem do ambiente, não da IA.',
     'Escreva numa linha o que você já "cultiva" em volta da IA que usa hoje: algum arquivo de contexto, regra ou exemplo?'),
   T('Os oito elementos do cultivo',
     'Todo agente, seja um assistente pessoal ou um agente de vendas, é cultivado com os mesmos oito ingredientes. Função: pelo que ele responde, um papel por vez. Contexto: o que ele precisa saber, e uma página boa vale mais que vinte despejadas. Ferramentas: o que ele pode operar, começando pela leitura; regras e limites: o que faz sem perguntar, o que pede confirmação, o que nunca faz. Exemplos são casos reais anotados, inclusive os ruins; memória é o que fica entre as sessões; avaliação pergunta se está bom e comparado a quê; feedback transforma cada falha em mudança no arquivo, não na conversa. Os quatro primeiros fazem o agente funcionar, e os quatro últimos fazem o agente melhorar.',
     'A página observa que a maioria das pessoas para no quarto elemento e reclama que "a IA não aprende". Conhecer os oito mostra onde está o buraco.',
     'Função; contexto; ferramentas; regras e limites; exemplos; memória; avaliação; feedback; software tradicional × IA cultivada.',
     'Um agente de triagem responde bem na primeira semana e depois repete os mesmos erros. Ele tem função, contexto, ferramentas e regras, mas nenhum exemplo anotado, nenhuma avaliação e nenhum feedback que volte ao arquivo.',
     'Marque quais dos oito elementos o seu agente tem hoje por escrito e quais existem só na sua cabeça.'),
   T('Cada volta do ciclo é uma safra',
     'O ciclo é o coração do método: processo, agente, execução, resultado, avaliação, feedback e, no fim, um agente melhor. O que muda entre uma safra e outra não é o modelo, é o que você anotou sobre onde ele errou e o que ajustou no ambiente. A página traz três regras. A avaliação gera linhas, não impressões: uma linha por falha no diário, e depois de dez linhas o padrão aparece. Corrija no arquivo, não na conversa; e autonomia se conquista por ciclo limpo, em três níveis: propõe e você executa; executa e você revisa; executa e reporta.',
     'Sem o ciclo, os quatro primeiros elementos viram um agente que estaciona. A regra da autonomia protege contra o erro mais caro: começar confiando demais.',
     'Diário de falhas; scorecard; mudança no ambiente; a ficha sobe de versão; nunca começa no nível 3.',
     'Um agente que rascunha e-mails de cobrança fica três semanas no nível 1, sem entradas novas no diário de falhas. Só então passa a enviar os rascunhos para revisão rápida, no nível 2.',
     'Abra um arquivo de diário de falhas com as quatro colunas da página e registre a próxima falha do seu agente.'),
   T('Os jardins pessoal e Jarvis',
     'A página chama de jardins os lugares onde o cultivo acontece. Na vida pessoal, bastam três ou quatro arquivos de texto e um hábito semanal, sem CRM nem API, em cinco frentes: decisões, saúde e rotina, dinheiro, estudo, e escrita e comunicação. O hábito que sustenta tudo é a revisão semanal de 20 minutos: ler a memória, escrever três linhas no diário de falhas, corrigir no arquivo e apagar o que já não é verdade. "Jarvis" é o nome popular do assistente pessoal agêntico, que não só responde, mas age no seu ambiente: lê e escreve arquivos, mexe no calendário, manda mensagem. A ferramenta vem pronta; o Jarvis, não, ele é cultivado com contexto, memória, ferramentas, regras, skills, avaliação e feedback.',
     'Agentes pessoais têm acesso à sua vida, e a página dedica uma seção à segurança, o lado que ninguém cultiva. Sem cerca, o jardim fica exposto.',
     'Revisão semanal de 20 minutos; propõe, executa e revisa, executa e reporta; credenciais em um lugar só; conteúdo externo é dado, não instrução; backup antes de operação destrutiva.',
     'Uma pessoa usa a IA como analista de gastos com uma planilha exportada do banco. A regra é nunca mover dinheiro, só mostrar. Depois de algumas semanas, aparecem padrões de gasto que ela nunca tinha visto.',
     'Escolha uma das cinco frentes pessoais e escreva o papel, uma regra e o que você quer avaliar.'),
   T('O jardim dos negócios',
     'Para a empresa, a página propõe parar de tratar a IA como software que se programa e passar a tratá-la como capacidade que a organização desenvolve. A automação rígida diz "se acontecer A, faça B, depois C" e quebra no primeiro caso que ninguém previu; o agente cultivado recebe um ambiente de trabalho, com papel, critérios, exemplos, limites e resultado esperado. O primeiro agente começa sempre no nível "propõe, humano executa": um processo, um agente, um indicador. A página sugere pontos de partida por área, como qualificação de leads em vendas, triagem em atendimento e conciliação no financeiro. E lista por que os projetos falham, com a menor correção para cada sintoma.',
     'Quando os projetos falham, o motivo raramente é o modelo, e sim falta de contexto, de processo e de feedback. Saber o diagnóstico evita trocar de ferramenta quando o problema é de cultivo.',
     '"O agente alucina": contexto ausente ou entulhado; "ninguém confia": sem avaliação por amostra; "parou de melhorar": feedback não volta ao ambiente; cargo que surge: gestor de agentes.',
     'Uma equipe de vendas reclama que o agente qualificador "quebrou em produção". O diagnóstico da página aponta exemplos só de casos fáceis; a correção é incluir os casos feios e as exceções nos exemplos.',
     'Escolha um processo da sua empresa com volume, regra clara e baixo custo de erro e defina o único indicador do primeiro agente.'),
   T('O kit: cinco arquivos e o curso',
     'Todo cultivo cabe em cinco arquivos de texto, iguais no jardim pessoal e no empresarial. A ficha do agente traz função, resultado esperado, dono humano, o que faz sozinho, o que pede confirmação e o que nunca faz, com versão e data. O contexto é o "Sobre mim" ou "Sobre a empresa"; os exemplos anotados reúnem bom, ruim e exceção aprovada, com o porquê; o diário de falhas tem uma linha por falha; o scorecard registra a revisão e a decisão de manter, subir ou voltar de nível. A área reúne o curso IA Cultivada, em página única e também em inglês e espanhol, os kits pessoal, Jarvis e empresa, o gerador de ficha, o diagnóstico de maturidade em oito perguntas e o repositório iacultivada no GitHub, com as skills /cultivar e /revisao-semanal. Para gerenciar os agentes na empresa, a página indica a área Gestão de IA; para construí-los, a área AGI-ready.',
     'Com os arquivos prontos, você não começa do zero nem depende de lembrar o que combinou com a IA. A página resume o ponto de partida: escolha um jardim, uma função e três regras; o resto é ciclo.',
     'Ficha do agente; contexto; exemplos anotados; diário de falhas; scorecard; kits; gerador; diagnóstico; /cultivar e /revisao-semanal.',
     'Uma dona de pequena loja faz o diagnóstico de oito perguntas, descobre que seu ponto fraco é avaliação e baixa o kit empresa. Preenche a ficha pelo gerador, direto no navegador, sem que nada saia do computador.',
     'Faça o diagnóstico em https://inematds.github.io/iacultivada/diagnostico/ e anote qual kit ele recomenda para você.')],
  ('Prompt: montar o jardim de um agente',
   'Leia https://eventos.inema.pro/ia-cultivada/ (área IA Cultivada do INEMA): os oito elementos, o ciclo, os três níveis de autonomia e os cinco arquivos do kit.\n\nMeu jardim: <vida pessoal, Jarvis ou negócio>\nA função do agente: <uma única responsabilidade>\nO que já existe: <ferramentas, documentos, exemplos que eu tenho>\n\nMonte os cinco arquivos em texto: 1) ficha do agente (função, resultado esperado, dono humano, faz sozinho, pede confirmação, nunca faz, versão v1.0 e data); 2) contexto de uma página; 3) modelo de exemplos anotados (bom, ruim, exceção aprovada, com o porquê); 4) cabeçalho do diário de falhas (data | o que quebrou | menor correção | instrução ou infra); 5) scorecard semanal. Comece no nível 1 (propõe, eu executo). Onde faltar informação, deixe <preencher> em vez de inventar.'),
  [('Área IA Cultivada','https://eventos.inema.pro/ia-cultivada/'),
   ('Curso IA Cultivada','https://inematds.github.io/iacultivada/'),
   ('Kits','https://inematds.github.io/iacultivada/kits/'),
   ('Diagnóstico','https://inematds.github.io/iacultivada/diagnostico/')],
  'ia-cultivada')

FIGURES[(2,2)] = dict(kind='grid',
    caption='Os quatro primeiros elementos fazem o agente funcionar; os quatro últimos fazem o agente melhorar.',
    items=['Função','Contexto','Ferramentas','Regras','Exemplos','Memória','Avaliação','Feedback'])
FIGURES[(2,3)] = dict(kind='flow',
    caption='O que muda de uma safra para outra não é o modelo: é o feedback que volta para o ambiente do agente.',
    items=['Processo','Agente','Execução','Avaliação','Feedback','Agente melhor'])
FIGURES[(2,4)] = dict(kind='stack',
    caption='Todo agente começa no nível 1 e só sobe depois de semanas sem entrada no diário de falhas.',
    items=[('Nível 1','propõe, você executa'),('Nível 2','executa, você revisa'),('Nível 3','executa e reporta')])
FIGURES[(2,6)] = dict(kind='columns',
    caption='Os cinco arquivos são os mesmos no jardim pessoal e no empresarial: muda o conteúdo, não a estrutura.',
    items=[('Ficha do agente','função e limites'),('Contexto','sobre mim ou empresa'),('Exemplos','bom, ruim, exceção'),('Diário de falhas','uma linha por falha'),('Scorecard','revisão semanal')])
