"""Trilha 2 — Ferramentas e ambiente de agentes. Fontes: inemaeventos/claude-codex/index.html, inemaeventos/codex-claude/index.html, inemaeventos/oswork/index.html + oswork/CONTEUDO.md + shared/acesso.json (lidas em 28/09/2026)."""
MODULES=[]
FIGURES={}
def M(title,goal,lab,steps,check,answer,topics,snippet,sources,slug):
    MODULES.append(dict(title=title,goal=goal,lab=lab,steps=steps,check=check,answer=answer,
                        topics=topics,snippet=snippet,sources=sources,slug=slug))
def T(title,what,why,keys,example,action):
    return dict(title=title,what=what,why=why,keys=keys,example=example,action=action)

# ---------------------------------------------------------------- módulo 0 — Claude → Codex
M('Claude → Codex: separe o cérebro do modelo',
  'Explicar por que o lock-in mora no runtime e como o método Auditar → Adaptar → Provar → Handoff leva o conhecimento do projeto para um núcleo portátil.',
  'Sua primeira auditoria em modo audit',
  ['Escolha um projeto seu que você conhece bem e anote quais arquivos de instrução ele tem hoje (CLAUDE.md, AGENTS.md, skills, memória).',
   'Cole o prompt do bloco copiável no seu agente e confira que a resposta é só inventário e plano: nenhum arquivo pode ter sido alterado.',
   'Verifique a classificação devolvida: cada skill como reutilizável, adaptador, nativo ou não resolvido, e cada trecho do CLAUDE.md como portátil ou resíduo.',
   'Responda por escrito as cinco perguntas de continuidade do passo Provar e marque as que ainda não têm resposta nos arquivos do projeto.'],
  'Um colega diz que migrar do Claude para o Codex é só copiar o CLAUDE.md para outro lugar. O que falta nessa ideia?',
  'Falta separar o que é portátil do que é resíduo e provar em sessão nova. Como diz a página, arquivo existir não é prova; o agente ter lido e usado é.',
  [T('A tese: separe o cérebro do modelo',
     'A área Claude → Codex parte de uma frase: "Não migre o seu cérebro. Separe o cérebro do modelo." O "cérebro" é tudo o que você acumulou num projeto: contexto, regras, decisões, tarefas, skills, handoffs e memória. Segundo a página, só CLAUDE.md e AGENTS.md estão presos ao provedor; todo o resto é Markdown portátil, texto simples que qualquer agente consegue ler. Quando esse material vive numa camada portátil dentro do projeto, Claude Code, Codex CLI, Gemini ou um modelo local em container viram apenas executores, isto é, programas que fazem o trabalho a partir desses arquivos. Trocar de modelo passa a ser trocar uma borda, não o centro. A área junta a tese, o método, um curso de 3 trilhas, um kit de scripts e mega-prompts que fazem isso na prática.',
     'Modelos mudam com frequência, por preço, acesso ou qualidade. Se o conhecimento do projeto estiver no lugar certo, cada troca custa pouco em vez de exigir reconstrução.',
     'cérebro = contexto, regras, decisões, tarefas, skills, handoffs e memória; Markdown portátil; executor; trocar a borda, não o centro',
     'Uma analista usa um assistente de código há meses e o time decide testar outro. Como as regras e decisões do projeto estão em arquivos Markdown no repositório, o novo executor lê os mesmos arquivos e continua o trabalho.',
     'Liste três coisas que o seu agente "sabe" hoje sobre um projeto e anote onde cada uma está gravada.'),
   T('O lock-in está no runtime',
     'Lock-in é ficar preso a um fornecedor porque sair dele custa caro. A página afirma: "O lock-in não está no modelo. Está no que você deixou dentro do runtime." Runtime é o programa que roda o agente, como o Claude Code ou o Codex CLI. Quem usa um assistente de código há alguns meses acumulou instruções, memória, skills, hooks e milhares de sessões num formato que só aquele runtime lê. A página descreve três mudanças: o lock-in é invisível até o dia da troca; o mesmo conhecimento pode servir a qualquer modelo; e você passa a ter menos dependência e mais controle. O conteúdo é durável, o formato é descartável, e misturar os dois é o que trava a migração.',
     'A área é para quem usa Claude Code ou Codex em projetos reais e teme a troca de modelo. Entender onde está a dependência mostra o que precisa sair do runtime antes que a troca seja obrigatória.',
     'lock-in; runtime; CLAUDE.md, memória nativa e sessões JSONL são armazenamento do trabalho, não o trabalho; conteúdo durável, formato descartável',
     'Um desenvolvedor descobre que as decisões mais importantes do projeto estão só no histórico de sessões do assistente. Ao trocar de ferramenta, ninguém sabe por que certas escolhas foram feitas, porque nada foi anotado fora do runtime.',
     'Abra um projeto seu e separe o que está em arquivos do repositório do que só existe na memória ou no histórico do assistente.'),
   T('O método: auditar antes de mudar',
     'O método tem quatro passos, nessa ordem: Auditar, Adaptar, Provar e Handoff, "nunca implementando antes de auditar". Auditar é fazer um inventário somente leitura dos dois runtimes: skills, comandos, subagentes, hooks e MCP; cada skill vira reutilizável, adaptador, nativo ou não resolvido. Adaptar é dividir o CLAUDE.md: regras portáteis vão para o AGENTS.md, e o que depende de plugin, hook ou menu do Claude fica no arquivo específico, que apenas importa o portátil. Provar é abrir uma sessão nova e fazer cinco perguntas de continuidade: objetivo e critério de pronto, uma regra com o arquivo de origem, a última decisão, a próxima ação e conflitos. Handoff é gravar decisões, pendências, próximos passos e caminhos num Markdown que a próxima sessão lê antes de agir.',
     'A ordem evita o erro mais caro: mudar arquivos antes de saber o que existe. E a regra de prova impede que você confunda arquivo criado com conhecimento realmente usado.',
     'Auditar → Adaptar → Provar → Handoff; MODE: audit; portátil × resíduo; cinco perguntas de continuidade; arquivo existir não é prova',
     'Uma equipe quer levar um projeto para o Codex. Primeiro roda a auditoria, que só lê e classifica; depois separa o CLAUDE.md; por fim abre uma sessão nova e confere se o agente responde a próxima ação citando o arquivo certo.',
     'Escreva as cinco perguntas de continuidade num arquivo e responda cada uma apontando o arquivo de origem.'),
   T('O núcleo portátil, arquivo por arquivo',
     'O núcleo portátil são sete lugares, cada um com um dono e uma regra de atualização. AGENTS.md guarda regras estáveis e ordem de leitura; context/overview.md, fatos verificados com fonte e data; context/current-state.md, o que funciona e o que está pendente; context/sources.md, de onde vem cada informação. context/decisions/ tem uma decisão aceita por arquivo; tasks/current.md traz objetivo, dono, critério de pronto e próxima ação; handoffs/latest.md é a continuação para a próxima sessão. A página avisa que esses nomes são convenção: nenhum runtime carrega essas pastas sozinho, quem manda ler é a ordem de leitura no topo do AGENTS.md. Cada informação tem um tipo: fato, preferência, hipótese ou decisão, e "provenance vence timestamp", ou seja, a origem pesa mais que a data e nada se apaga, usa-se superseded_by.',
     'Misturar fato com hipótese, ou decisão com preferência, faz o agente repetir erro antigo e contradizer o que já foi resolvido. Dono e data permitem promover uma informação para contexto aprovado, sempre com a sua aprovação.',
     'AGENTS.md; context/; decisions/; tasks/current.md; handoffs/latest.md; fato, preferência, hipótese, decisão; provenance vence timestamp; segredos fora do repositório',
     'Num projeto com decisões antigas em conflito, cada decisão aceita vira um arquivo em context/decisions/. Quando uma é substituída, ela não é apagada: ganha a marca superseded_by e o agente para de seguir a regra velha.',
     'Crie num projeto de teste o arquivo tasks/current.md com objetivo, dono, critério de pronto e próxima ação.'),
   T('Migrar ou ficar agnóstico',
     'A página separa a decisão em três níveis de esforço, não em opiniões. Nível 1 é importar no app, com um clique: rápido, mas limitado ao que o outro lado aceita, e o CLI do Codex, por exemplo, não tem import nativo. Nível 2 é migrar com o kit, com um comando: rodar os scripts do agente-claude-codex para auditar, adaptar, instalar o núcleo, portar skills e provar. Nível 3 é a camada pessoal portátil, duradoura: o conhecimento vive no projeto e o runtime fica intercambiável. Ficar agnóstico, isto é, não depender de nenhum modelo específico, é o nível 3, e segundo a página é o único que sobrevive à próxima troca. Agnóstico não é abandonar o Claude: você continua escolhendo o executor por tarefa.',
     'Nem todo mundo precisa do nível 3 agora. A página lista quando migrar já, por custo, acesso ou política, e quando vale ficar agnóstico, como ao usar dois executores ou ter trabalho de cliente.',
     'Nível 1 importar; Nível 2 migrar com o kit; Nível 3 camada pessoal portátil; migrar agora × ficar agnóstico; custo de não fazer nada',
     'Um consultor precisa usar o Codex nesta semana por política de um cliente e tem poucas skills, quase todas em Markdown puro: é caso de migrar agora. Outro já trocou de ferramenta uma vez e não quer refazer: é caso de ficar agnóstico.',
     'Leia as duas listas da página ("Migre agora se…" e "Fique agnóstico se…") e marque quantos itens valem para você em cada uma.'),
   T('Curso, kit e o primeiro passo',
     'O curso Claude → Codex: migre ou fique agnóstico é aberto, em português, com versões em inglês e espanhol; segundo o currículo, são 3 trilhas, 18 módulos e 108 tópicos. A Trilha 1 cobre fundamentos e vocabulário, a Trilha 2 é o kit comando por comando e a Trilha 3 traz seis projetos sobre um sistema real. O kit agente-claude-codex é bash mais Markdown, em três formas de uso: scripts, mega-prompts e o template do núcleo portátil. O doctor.sh responde "meu ambiente está pronto?" e o audit.sh grava um relatório somente leitura; há ainda adapt-instructions.sh, init-core.sh, sync-skills.sh com polyskill, readback-test.sh, drift-report.sh e promover-memoria.sh. A página resume: "O melhor primeiro passo é um projeto seu, em modo audit."',
     'O curso explica o porquê e o kit faz o trabalho sem apagar nada: nada em ~/.claude ou ~/.codex é copiado em massa ou apagado, e instalar skill faz backup ao lado. Começar pela auditoria mostra em uma sessão o que é portátil e o que depende de hook.',
     'curso de 3 trilhas; kit agente-claude-codex; doctor.sh; audit.sh; mega-prompts A e B; Mapa do tema; área irmã Codex + Claude',
     'Uma gestora de TI quer avaliar a troca de ferramenta sem risco. Ela clona o kit, roda o doctor.sh, lê a auditoria e só depois decide qual nível de migração vale a pena para o time.',
     'Abra o guia do kit agente-claude-codex e leia o que o doctor.sh verifica antes de rodar qualquer outro script.')],
  ('Prompt: auditoria somente leitura do seu projeto',
   'MODE: audit\nLeia https://eventos.inema.pro/claude-codex/ para entender o método Auditar → Adaptar → Provar → Handoff.\nDepois, sem alterar nenhum arquivo, faça um inventário deste projeto: <caminho da pasta do seu projeto>.\n1. Liste instruções (CLAUDE.md, AGENTS.md), skills, comandos, hooks e MCP que você encontrar.\n2. Classifique cada skill como reutilizável, adaptador, nativo ou não resolvido.\n3. Separe o CLAUDE.md em linhas portáteis (vão para o AGENTS.md) e resíduo específico do Claude.\n4. Diga quais das cinco perguntas de continuidade (objetivo e critério de pronto, uma regra com arquivo de origem, última decisão, próxima ação, conflitos) os arquivos atuais já respondem.\nDevolva só o relatório e um plano. Não implemente nada.'),
  [('Área Claude → Codex','https://eventos.inema.pro/claude-codex/'),
   ('Curso Claude → Codex','https://inematds.github.io/curso-claude-codex/'),
   ('Guia do kit agente-claude-codex','https://inematds.github.io/agente-claude-codex/guia/'),
   ('Mapa do tema','https://inema.club/guias/claude-codex.html')],
  'claude-codex')

FIGURES[(0,2)]=dict(kind='columns',caption='As três mudanças da página: o problema só aparece na troca, o conhecimento pode servir a qualquer modelo e o controle volta para você.',
  items=[('Lock-in','invisível até a troca'),('Mesmo saber','qualquer modelo'),('Mais controle','modelo reversível')])
FIGURES[(0,3)]=dict(kind='flow',caption='A ordem importa: primeiro só ler e classificar, depois adaptar, provar em sessão nova e registrar o handoff.',
  items=['Auditar','Adaptar','Provar','Handoff'])
FIGURES[(0,4)]=dict(kind='tree',caption='Os sete lugares do núcleo portátil: nenhum runtime lê isso sozinho, é a ordem de leitura no AGENTS.md que manda.',
  items=[('AGENTS.md',0),('context/',0),('overview.md',1),('current-state.md',1),('sources.md',1),('decisions/',1),('tasks/current.md',0),('handoffs/latest.md',0)])
FIGURES[(0,5)]=dict(kind='stack',caption='Cada nível custa mais esforço uma vez, e só o terceiro sobrevive à próxima troca de modelo.',
  items=[('Nível 1','importar no app'),('Nível 2','migrar com o kit'),('Nível 3','camada portátil')])

# ---------------------------------------------------------------- módulo 1 — Codex + Claude
M('Codex + Claude: um faz, o outro confere',
  'Explicar como usar Claude e Codex no mesmo projeto, com os seis níveis do kit Use Both, o cartão de rotas e a diferença entre claudex e Use Both.',
  'Seu plano revisado pelo outro',
  ['Escolha uma tarefa pequena e escreva num arquivo plan-v1.md o briefing, o plano e o critério de aceite.',
   'Rode o comando do bloco copiável (ou o caminho inverso com claude -p) e confirme que o arquivo review.md foi criado e que plan-v1.md não mudou.',
   'Leia a revisão e marque cada achado como resolvido, rejeitado com motivo ou pendente; não passe de duas rodadas.',
   'Grave um handoff curto com o estado do plano, as decisões e a próxima ação, para a próxima sessão ler antes de agir.'],
  'Claude escreveu o plano e o próprio Claude, na mesma sessão, aprovou. Por que isso não basta?',
  'Porque o modelo que escreveu tende a aprovar o próprio plano, e duas IAs concordando não é prova independente. Quem decide são os testes e a sua aprovação.',
  [T('Um planeja, o outro critica',
     'A área Codex + Claude tem como tese: "Um planeja, o outro critica. Use os dois juntos." A ideia é que Claude e Codex se completam quando cada um faz uma parte e o outro confere o artefato real, isto é, o arquivo, o diff ou a imagem de verdade. A regra que atravessa tudo: o segundo assistente recebe o mesmo briefing e o artefato real, nunca um resumo vago do que o primeiro fez. A página é o ponto de encontro do INEMA sobre as duas ferramentas e reúne os seis níveis do kit Use Both, a tabela de quem faz o quê e os cards de todos os cursos e projetos. Para migrar de um para o outro, o caminho continua sendo a área irmã Claude → Codex.',
     'É para quem já tem Claude Code e Codex e não quer escolher um só. Um segundo olhar, de outro modelo, pega falhas que o autor tende a deixar passar.',
     'um faz, o outro confere; artefato real; mesmo briefing; não é Claude ou Codex; área irmã Claude → Codex',
     'Uma desenvolvedora escreve o plano de uma feature com um assistente e entrega o mesmo arquivo ao outro, só para leitura. A crítica aponta um teste faltando antes de qualquer linha de código ser escrita.',
     'Pegue um plano ou documento seu recente e anote quem poderia revisá-lo com o mesmo briefing, sem resumo.'),
   T('Os seis níveis do Use Both',
     'O kit Use Both organiza o uso conjunto em seis níveis de fluxo de trabalho, com prompts prontos e duas skills pequenas. Nível 1 é deixar as duas discutirem: uma escreve o plano, a outra critica o mesmo arquivo, só lendo, em no máximo duas rodadas. Nível 2, opcional, é gerar imagens, só se houver ferramenta de imagem na sessão e depois de conferir acesso e cobrança. Nível 3 é dividir construir e revisar: uma constrói num branch, a outra revisa o diff com o briefing e o resultado dos testes. Nível 4 é o uso supervisionado do computador, com senha, pagamento e envios importantes sob o seu controle; nível 5 é uma meta com condição de parada, com sucesso observável e limites de arquivos, rodadas e gasto. Nível 6 é handoff e prime: o handoff grava o estado num arquivo portátil e o prime faz o próximo assistente ler e verificar esse estado antes de continuar.',
     'Os níveis dão uma escada: dá para começar pela discussão de um plano e subir só quando precisar. Cada nível já traz o limite que evita gasto ou ação sem controle.',
     'discutir; gerar imagens; construir e revisar; uso supervisionado do computador; meta com condição de parada; handoff e prime',
     'Um time usa o nível 3: um assistente implementa a correção num branch e o outro revisa o diff junto com a saída dos testes. O que entra no projeto é decidido pelos testes e pela aprovação humana.',
     'Descubra em qual dos seis níveis você já trabalha hoje e qual seria o próximo.'),
   T('Quem faz o quê: o cartão de rotas',
     'O cartão de rotas é uma tabela do kit que diz, para cada tarefa, quem faz a primeira passada, quem faz a segunda e qual é a linha de chegada. Planejar o trabalho: Claude / Opus planeja, o Codex critica as premissas, e o resultado é um plano com escopo e testes de aceite. Construir uma feature: Claude / Opus constrói, o Codex revisa o diff, e o pronto é testes passando e achados resolvidos. Atacar um bug difícil: Codex com uma meta delimitada, testes e um checkpoint humano. Trocar de sessão ou de modelo: snapshot de handoff, e o prime confere o estado atual. A página avisa que são "escolhas editoriais, não ranking medido de modelos": experimente e fique com a rota que produzir melhor evidência.',
     'Ter uma rota inicial evita discutir do zero a cada tarefa. Saber que ela não é benchmark evita tratá-la como verdade fixa.',
     'primeira passada; segunda passada; linha de chegada; escolhas editoriais, não ranking; modelos e cobrança mudam conforme a conta',
     'Uma analista precisa revisar um documento de requisitos. Pela rota, qualquer um dos dois escreve e o outro confere fatos e requisitos; o pronto é toda afirmação exigida ter evidência.',
     'Escolha uma tarefa da sua semana e preencha as três colunas do cartão: primeira passada, segunda passada e linha de chegada.'),
   T('Um caminho só: claudex × Use Both',
     'A página organiza cursos e projetos num caminho: entender, migrar ou ficar agnóstico, usar os dois juntos e automatizar o debate. O elo comum são os arquivos Markdown do projeto, como AGENTS.md, tasks e handoffs, que qualquer runtime lê. Nesse caminho aparecem duas ferramentas diferentes. O claudex é um plugin do Claude Code, ou seja, software: o Claude escreve o PLAN.md e o Codex critica de 3 ângulos, em loop até LGTM ou N rodadas. O Use Both é um kit de método, com guia, prompts, templates e 2 skills, cobrindo os seis fluxos, de forma manual ou semiautomática. A página resume: são complementares; plano grande, claudex; o resto, como revisar diff, meta com condição de parada e trocar de sessão, Use Both.',
     'Saber em que camada cada ferramenta atua evita instalar software para um problema de método, ou o contrário.',
     'Entender → Migrar → Usar os dois → Automatizar o debate; claudex = software; Use Both = método; LGTM; complementares',
     'Um líder técnico tem um plano de arquitetura grande e usa o claudex para o debate automático. No dia a dia, para revisar diffs e trocar de sessão, o time segue os níveis do Use Both.',
     'Compare na tabela claudex × Use Both a linha "Limite" e anote quantas rodadas cada um recomenda.'),
   T('Imagem com o Codex, peça a peça',
     'A página traz um caso real: quem tem assinatura do Codex e usa o gerador de imagem dele, o image_gen, que no INEMA é chamado de "imagem 2.5". Hoje, no INEMA, o Claude Code chama codex exec em modo não interativo e pede ao image_gen um PNG numa pasta; se o Codex falhar ou não houver crédito, cai para o modelo local FLUX.2 klein. Cada geração consome crédito da assinatura, por isso roda só quando autorizada, e a imagem é conferida depois, porque o texto das bordas pode vir inventado. O kit propõe o nível 2 peça a peça: confirmar antes a ferramenta e a cobrança, nunca trocar sozinho para uma API paga, salvar o arquivo real no projeto e abrir no tamanho de uso. A diferença, nas palavras da página: o do INEMA é em lote e automático, com fallback local; o do kit é manual, com mais checagem de custo e de revisão.',
     'Imagem gerada tem custo e erros visíveis. As duas abordagens mostram como equilibrar automação com conferência antes de usar o arquivo.',
     'image_gen; codex exec; fallback FLUX.2 klein; checar antes, inspecionar depois; versões irmãs em vez de sobrescrever',
     'Um designer gera a capa de um material com o Codex. Antes de publicar, abre o arquivo no tamanho real, encontra uma palavra inventada na borda e salva a correção como versão irmã, sem apagar o original.',
     'Antes da próxima imagem que você gerar, anote qual ferramenta vai usar e como ela cobra.'),
   T('Primeiro passo e todos os projetos',
     'A página resume o começo assim: "O melhor primeiro passo: um plano seu, revisado pelo outro." Escolha uma tarefa pequena, escreva o briefing e o critério de aceite, peça o plano a um e a crítica ao outro, sobre o mesmo arquivo, no máximo duas rodadas, e faça handoff antes de fechar a sessão. A área reúne seis cursos: Claude → Codex (PT, EN e ES), Codex Básico, Master Codex, iClaudeX, MakeClaudeX e DeepClaudeX. Também reúne kits e referências: agente-claude-codex, Use Both, claudex no GitHub, Codex Cheat Sheet e o Mapa do tema no INEMA.CLUB. A página cita um vídeo externo de Mark Kashef, que o kit Use Both acompanha, como fonte de opiniões do autor, sem benchmark; o resumo dele fica no RESUMO-VIDEO.md do repositório do kit.',
     'Um primeiro ciclo curto mostra na prática o valor do segundo olhar. Os cursos e kits deixam claro onde aprofundar cada etapa.',
     'um plano seu, revisado pelo outro; no máximo duas rodadas; Codex Básico; Master Codex; iClaudeX; MakeClaudeX; DeepClaudeX; Use Both; claudex; Codex Cheat Sheet',
     'Uma coordenadora pede ao Claude o plano de uma rotina de relatórios e ao Codex a crítica, só lendo. Na segunda rodada o plano fecha, e ela grava o handoff para retomar no dia seguinte.',
     'Abra o guia do Use Both e leia o nível 1 antes de rodar o seu primeiro plano revisado.')],
  ('Comando: Codex revisa seu plano, só lendo',
   'codex exec --sandbox read-only -c model_reasoning_effort=medium \\\n  --output-last-message review.md \\\n  \'Leia plan-v1.md. Aponte falhas de correção e testes faltando, com evidência, impacto e a menor correção. Não altere arquivos.\'\n\n# Caminho inverso (Codex escreveu, Claude revisa):\nclaude -p --model opus --effort medium \\\n  \'Leia plan-v1.md e revise só lendo: falhas, suposições e testes faltando. Não altere arquivos.\' > review-claude.md'),
  [('Área Codex + Claude','https://eventos.inema.pro/codex-claude/'),
   ('Guia do Use Both','https://inematds.github.io/use-both-claude-codex/guia/'),
   ('claudex no GitHub','https://github.com/inematds/claudex'),
   ('Curso Claude → Codex','https://inematds.github.io/curso-claude-codex/')],
  'codex-claude')

FIGURES[(1,2)]=dict(kind='grid',caption='Os seis níveis do Use Both, do debate de um plano até a troca de sessão; cada um traz o seu próprio limite.',
  items=['Discutir','Imagens','Construir','Computador','Meta c/ parada','Handoff/prime'])
FIGURES[(1,3)]=dict(kind='columns',caption='Quatro linhas do cartão de rotas: quem começa e quem confere. São escolhas editoriais, não ranking medido.',
  items=[('Planejar','Claude; Codex critica'),('Construir','Claude; Codex revisa'),('Bug difícil','Codex com meta'),('Trocar sessão','handoff e prime')])
FIGURES[(1,4)]=dict(kind='flow',caption='Cursos e kits cobrem etapas de um mesmo caminho, ligadas pelos arquivos Markdown do projeto.',
  items=['Entender','Migrar','Usar os dois','Automatizar debate'])
FIGURES[(1,5)]=dict(kind='flow',caption='O nível 2 do kit, peça a peça: conferir custo antes e o arquivo real depois, sem sobrescrever o original.',
  items=['Checar ferramenta','Gerar rascunho','Salvar arquivo','Inspecionar','Versões irmãs'])

# ---------------------------------------------------------------- módulo 2 — OSWork
M('OSWork: qual edição é pra você',
  'Explicar o que é o OSWork, o que se constrói nele e qual das cinco edições (v2, v6.2, v6, v5, Quick) combina com a experiência e o tempo de cada pessoa.',
  'Sua escolha de edição',
  ['Anote sua situação: experiência com IA, se já usou terminal e quanto tempo por semana você tem.',
   'Cole o prompt do bloco copiável no Claude ou no ChatGPT e confira que a resposta indica uma edição citando a frase da página que justifica a escolha.',
   'Abra o curso indicado pelo link da área e confirme que o número de aulas ou módulos bate com o que a página descreve.',
   'Faça a primeira tarefa pequena: crie uma pasta de treino e guarde nela o primeiro resultado e uma dúvida registrada.'],
  'Uma pessoa de 45 anos, sem familiaridade com IA e com pouco tempo, quer começar. Qual edição a página indica e por quê?',
  'O OSWork Quick (ou o v5): a página descreve o Quick como versão curta e visual para profissionais 40+, com sete aulas e cerca de 77 minutos, e o v5 como sete aulas sem programação para o mesmo público.',
  [T('IA como sistema de trabalho',
     'O OSWork se apresenta como "IA como sistema de trabalho" e "do chat ao seu ambiente de agentes". Um agente é uma IA que executa tarefas com ferramentas e arquivos, e não só responde numa conversa. O curso ensina a organizar arquivos, instruções, memória e ferramentas em um sistema de trabalho que você consegue verificar. A frase central da página é: "Sua próxima conversa pode começar de onde a anterior parou." Para isso, o OSWork ensina a transformar pedidos soltos em trabalho organizado: definir o objetivo, escolher o contexto, executar uma tarefa pequena e conferir o resultado. Você começa no chat e avança até um bot restrito e a operação supervisionada em uma VPS, um servidor alugado na internet.',
     'Sem organização, cada conversa com a IA recomeça do zero. Um sistema com arquivos e regras guarda o que já foi decidido e deixa o resultado conferível.',
     'sistema de trabalho; do chat ao ambiente de agentes; objetivo, contexto, tarefa pequena, conferência; bot restrito; VPS supervisionada',
     'Um gestor pede toda semana o mesmo relatório à IA e explica tudo de novo a cada vez. Com uma pasta de projeto e instruções próprias, a próxima conversa já começa com o contexto certo.',
     'Escreva em uma frase qual tarefa sua recomeça do zero toda vez que você abre o chat.'),
   T('Cinco edições, cinco caminhos',
     'A página oferece "cinco caminhos para organizar seu trabalho com IA" e pede para escolher pela sua experiência e pelo tempo disponível. OSWork v2 é o percurso técnico. OSWork v6.2 é o percurso completo, passo a passo. OSWork v6 é para iniciantes, visual. OSWork v5 é para iniciantes 40+. OSWork Quick é direto ao ponto. Segundo a página, há cursos e vídeos em português, espanhol e inglês; pelo acesso da área, v6.2 e v6 têm links próprios em EN e ES.',
     'Escolher a edição certa evita desistir no primeiro terminal ou se entediar com o básico. A mesma ideia chega por caminhos de profundidade diferente.',
     'v2 técnico; v6.2 completo passo a passo; v6 iniciantes visual; v5 iniciantes 40+; Quick direto ao ponto',
     'Numa equipe, o desenvolvedor segue o v2 e a coordenadora administrativa, sem experiência com IA, começa pelo Quick. Os dois aprendem a mesma lógica de organizar o trabalho, cada um no seu ritmo.',
     'Marque, entre as cinco edições, as duas que mais combinam com você hoje.'),
   T('v2 e v6.2: o percurso completo',
     'O OSWork v2 é o percurso técnico: oito módulos, quatro trilhas e 48 tópicos. Vai do chat ao terminal e Codex, arquivos, Skills, Git, bot no Telegram e operação supervisionada em VPS, e inclui kit de prática. Os oito módulos são: Modelos; Chat, Work e Desktop; Terminal e Codex na prática; Pastas, Markdown e segredos; AGENTS, Skills e memória; Git e GitHub sem perder trabalho; Telegram como interface de trabalho; e VPS do zero e operação 24/7. O OSWork v6.2 é esse mesmo percurso refeito para quem está começando: oito módulos e 48 aulas de uns 15 minutos, com passo a passo visual e um glossário dos termos técnicos. No v2, o aluno marca tópicos lidos, registra dúvidas, faz notas e exporta a jornada; o progresso fica no navegador e é separado por idioma.',
     'Quem quer chegar até bot e servidor precisa do percurso inteiro. O v6.2 permite fazer esse caminho mesmo sem base técnica.',
     'v2: 8 módulos, 4 trilhas, 48 tópicos, kit; v6.2: 48 aulas de ~15 min, glossário; Codex; Skills; Git; Telegram; VPS',
     'Uma analista quer automatizar consultas por Telegram, mas nunca abriu um terminal. Ela escolhe o v6.2, que cobre os mesmos módulos do v2 em aulas curtas e visuais.',
     'Leia os títulos dos oito módulos do v2 na página e marque até qual deles você quer chegar.'),
   T('v6, v5 e Quick: para quem começa',
     'Três edições são para iniciantes e não pedem instalação nem programação. O OSWork v6 tem sete aulas de uns 15 minutos com telas de chat simuladas, antes e depois reais e passo a passo visual; você monta pastas por assunto, uma ficha com as suas regras, um molde de pedido e uma rotina de conferência, sem instalar nada. O OSWork v5 é para profissionais 40+ com pouca familiaridade com IA: sete aulas de 20 a 25 minutos para organizar pastas, orientações, pedidos reutilizáveis e uma rotina de conferência, sem programação. O OSWork Quick é a versão curta e visual para profissionais 40+: sete aulas e cerca de 77 minutos de estudo, com os mesmos assuntos do v5 e menos texto. O Quick também existe em vídeo, com avatar e voz do Nei, ilustrações e legendas SRT, em português, espanhol e inglês.',
     'Para quem está começando, o ganho vem de organizar e conferir, não de ferramentas técnicas. Essas edições entregam isso em pouco tempo.',
     'v6: 7 aulas de ~15 min, visual, sem instalar; v5: 7 aulas de 20 a 25 min, 40+; Quick: 7 aulas, ~77 min, também em vídeo',
     'Um contador de 50 anos quer usar IA com mais segurança. Assiste ao OSWork Quick em vídeo e sai com pastas por assunto e uma rotina para conferir as respostas.',
     'Assista à primeira aula do OSWork Quick em vídeo no seu idioma.'),
   T('O que você constrói',
     'A página lista o que se constrói no percurso: uma pasta de projeto com entradas, saídas e instruções próprias; uma memória de decisões e falhas, junto de uma Skill reutilizável; um histórico Git para revisar e recuperar mudanças; e um bot de consulta com dados fictícios e um plano de operação. Uma Skill é um procedimento empacotado que o agente reaproveita; Git é um sistema que guarda versões dos arquivos. A seção do kit diz: "Seu primeiro ambiente começa com arquivos reais." O kit reúne modelos de AGENTS.md, memória, decisões, registro de falhas, contrato de tarefa, Skill de relatório e plano de VPS, e inclui um bot Python com autoteste offline. O bot de treino é determinístico: não chama um modelo de IA nem executa mensagens como comandos.',
     'Terminar com arquivos concretos, e não só com anotações, é o que torna o aprendizado reaproveitável no trabalho. Os modelos do kit poupam o começo do zero.',
     'pasta de projeto; memória de decisões e falhas; Skill; Git; bot de consulta com dados fictícios; kit ZIP; bot determinístico',
     'Uma assistente de projetos baixa o kit, adapta o contrato de tarefa para o relatório mensal da equipe e passa a registrar cada falha numa linha do registro de falhas.',
     'Baixe o kit ZIP da área e abra o modelo de contrato de tarefa.'),
   T('Comece com uma tarefa pequena',
     'A página orienta: "Comece com uma tarefa pequena." São três passos: escolher o primeiro módulo e comparar duas opções disponíveis no seu ambiente; criar uma pasta de treino e adaptar o contrato de tarefa do kit; guardar o resultado, registrar uma dúvida e voltar à sua jornada. Na seção "Antes de começar", a página responde que dá para iniciar pelos fundamentos sem programação, e que os laboratórios técnicos apresentam terminal, Git e Python passo a passo. O conteúdo pode ser lido sem cadastro; assinaturas, consumo de API e contratação de VPS são serviços separados, escolhidos pelo aluno. E o curso não promete um agente autônomo sem supervisão: ensina limites, verificação, logs e recuperação.',
     'Uma tarefa pequena mostra resultado rápido e revela o que falta organizar. Saber o que é pago à parte evita surpresa.',
     'tarefa pequena; pasta de treino; contrato de tarefa; sem programação no início; leitura sem cadastro; serviços pagos à parte; operação supervisionada',
     'Uma professora cria uma pasta de treino, adapta o contrato de tarefa para montar uma lista de exercícios e guarda o resultado com uma dúvida anotada para a aula seguinte.',
     'Crie hoje uma pasta de treino e escreva nela o contrato da sua primeira tarefa pequena.')],
  ('Prompt: qual edição do OSWork é pra mim',
   'Leia https://eventos.inema.pro/oswork/ e compare as cinco edições do OSWork (v2, v6.2, v6, v5 e Quick).\nMinha situação: <sua experiência com IA>, <já usei ou nunca usei terminal>, <quanto tempo por semana tenho>, <o que quero construir>.\n1. Indique uma edição e cite a frase da página que justifica a escolha.\n2. Diga quantas aulas ou módulos ela tem, segundo a página.\n3. Proponha a minha primeira tarefa pequena, seguindo a seção "Comece com uma tarefa pequena".\nUse só o que está na página; se algo não estiver lá, diga que não está.'),
  [('Área OSWork','https://eventos.inema.pro/oswork/'),
   ('OSWork v2','https://inematds.github.io/oswork/'),
   ('OSWork v6.2','https://inematds.github.io/oswork-v62/'),
   ('Vídeos do OSWork Quick','https://inematds.github.io/oswork-quick/videos/')],
  'oswork')

FIGURES[(2,2)]=dict(kind='columns',caption='As cinco edições do OSWork: escolha pela sua experiência e pelo tempo que você tem.',
  items=[('v2','percurso técnico'),('v6.2','completo passo a passo'),('v6','iniciantes, visual'),('v5','iniciantes 40+'),('Quick','direto ao ponto')])
FIGURES[(2,3)]=dict(kind='grid',caption='Os oito módulos do percurso v2 (e do v6.2), do chat à operação em VPS.',
  items=['Modelos','Chat/Work','Terminal/Codex','Pastas/MD','AGENTS/Skills','Git/GitHub','Telegram','VPS 24/7'])
FIGURES[(2,5)]=dict(kind='stack',caption='O que você sai construindo: cada camada apoia a seguinte, da pasta ao bot com plano de operação.',
  items=[('Pasta de projeto','entradas, saídas, regras'),('Memória e Skill','decisões e falhas'),('Histórico Git','revisar e recuperar'),('Bot de consulta','dados fictícios')])
FIGURES[(2,6)]=dict(kind='flow',caption='O primeiro passo sugerido pela página: pequeno, com resultado guardado e uma dúvida registrada.',
  items=['Primeiro módulo','Pasta de treino','Contrato de tarefa','Guardar e anotar'])
